### REGISTER
POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
  "email": "admin&tunas.id",
  "password": "rahasia"
}

### LOGIN
POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
  "email": "admin&tunas.id",
  "password": "rahasia"
}

### TOKEN
POST http://localhost:3000/api/v1/user/token
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzkyNDE2MDAwMDAsInVzZXJJZCI6ImM2NTkzNGIyLWMwYzEtMTFlZC1hZTUwLWY0NWM4OWIxMWIxMyJ9.7labBIsy166v-m7cB1aMc8fHVibid9IkuUjE_HGiGwA",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzkyNDE2MDAwMDAsInVzZXJJZCI6ImM2NTkzNGIyLWMwYzEtMTFlZC1hZTUwLWY0NWM4OWIxMWIxMyJ9.7labBIsy166v-m7cB1aMc8fHVibid9IkuUjE_HGiGwA"
}

###
GET http://localhost:3000/api/v1/user/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

################
### CATEGORY ###
################

### STORE CATEGORY
POST http://localhost:3000/api/v1/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

{
  "category": "Bread",
  "imageUrl": "notfound.png"
}

### GET CATEGORY BY ID
GET http://localhost:3000/api/v1/category/cbf969a8-b5a1-11ed-b28a-f45c89b11b13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A


### GET ALL CATEGORY
GET http://localhost:3000/api/v1/category?pageIndex=0&pageSize=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A


### UPDATE CATEGORY
PUT http://localhost:3000/api/v1/category/cbf969a8-b5a1-11ed-b28a-f45c89b11b13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

{
  "category": "Vegetable",
  "imageUrl": "notfound.png"
}

### DESTROY CATEGORY
DELETE http://localhost:3000/api/v1/category/595841d0-b5dd-11ed-8e95-f45c89b11b13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A


### ADD PRODUCT
POST http://localhost:3000/api/v1/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A


{
  "name": "Garlic Brad",
  "price": 10,
  "weight": 1000,
  "perUnit": 100,
  "description": "Serve with coffe for better experience",
  "imageUrl" : "notfound.png",
  "categoryId": "5b1cb6d6-d0b3-11ed-ba83-8c859078c9ec"
}

### UPDATE PRODUCT
PUT http://localhost:3000/api/v1/product/7d0e2b56-b95e-11ed-abfe-f45c89b11b13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

{
  "name": "Banana",
  "price": 10,
  "weight": 1000,
  "perUnit": 100,
  "description": "Good for health",
  "imageUrl" : "https://carrot.png",
  "categoryId": "cbf969a8-b5a1-11ed-b28a-f45c89b11b13"
}

### GET ALL PRODUCT
GET http://localhost:3000/api/v1/product?pageIndex=0&pageSize=10&isTop=false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### DELETE PRODUCT
DELETE http://localhost:3000/api/v1/product/03d5d220-7d54-11ed-b6e2-f45c89b11b13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### PRODUCT BY ID
GET http://localhost:3000/api/v1/product/a2e50426-b95e-11ed-abfe-f45c89b11b13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### PRODUCT BY CATEGORY
GET http://localhost:3000/api/v1/product/category/8c2c184e-11d2-11ec-82a8-0242ac130003

### TOP PRODUCT
POST http://localhost:3000/api/v1/product/top/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### TOP RECOMMENDATION
POST http://localhost:3000/api/v1/product/recommendation/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A


###################
### TRANSACTION ###
###################

### MAKE TRANSACTION
POST http://localhost:3000/api/v1/transaction
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

{
  "data": [
    {
      "productId": "64dddb64-d0b3-11ed-ba83-8c859078c9ecs",
      "total": 2
    }
  ]
}

### GET TRANSACTION BY ID
GET http://localhost:3000/api/v1/transaction/de0f77d0-7dcb-11ed-b6b4-f45c89b11b13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### GET TRANSACTION BY USER ID
GET http://localhost:3000/api/v1/transaction/user/bf80843e-0dba-4b0c-bcb4-faeaec5e53fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### DESTROY TRANSACTION BY ID
DELETE http://localhost:3000/api/v1/transaction/de0f77d0-7dcb-11ed-b6b4-f45c89b11b13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

#######################
### CART & WISHLIST ###
#######################

### STORE CART
POST http://localhost:3000/api/v1/cart/7d3d04f0-c63b-11ed-8d33-f45c89b11b13/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### DESTROY CART
DELETE http://localhost:3000/api/v1/cart/c85d97b0-c63b-11ed-96de-f45c89b11b13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### GET USER CART
GET http://localhost:3000/api/v1/cart?pageIndex=0&pageSize=10&search=garlic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### ADD WISHLIST
POST http://localhost:3000/api/v1/wishlist/bf80843e-0dba-4b0c-bcb4-faeaec5e53fa/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### GET USER WISHLIST
GET http://localhost:3000/api/v1/wishlist/bf80843e-0dba-4b0c-bcb4-faeaec5e53fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### DESTROY USER WISHLIST
DELETE http://localhost:3000/api/v1/wishlist/bf80843e-0dba-4b0c-bcb4-faeaec5e53fa/8c934506-7d64-11ed-8570-f45c89b11b13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

###################
### USER & ROLE ###
###################

### GET ALL USER
GET http://localhost:3000/api/v1/user/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### GRANT ROLE TO USER
POST http://localhost:3000/api/v1/user/role/fc81ccd7-98aa-11ec-ba07-b78370c9a109/5d3337d8-98ab-11ec-ba07-c940688411f4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### REVOTE ROLE FROM USER
DELETE http://localhost:3000/api/v1/user/role/1/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### GET ALL ROLES
GET http://localhost:3000/api/v1/role/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

### SAVE ROLE
POST http://localhost:3000/api/v1/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

{
  "name" : "USER"
}

### GET ROLE BY ID
GET http://localhost:3000/api/v1/role/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A

###
GET http://localhost:3000/api/v1/user/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A


### USER
GET http://localhost:3000/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODAzNzA5NjEyMDA0NTMwMDAsInVzZXJJZCI6IjczZjExZWU2LWQwNWQtMTFlZC04OGI4LThjODU5MDc4YzllYyJ9.-URCFKz-l8nitKdHyK7iNsWdin4DQLvOeYGk4bZeF9A
