###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username" : "admins",
  "password" : "password"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username" : "admins",
  "password" : "password"
}

###
GET http://localhost:8080/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
GET http://localhost:8080/category/2d38b209-ab3f-11ec-bae3-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
POST http://localhost:8080/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

{
  "category": "",
  "imageUrl": ""
}

###
PUT http://localhost:8080/category/17c67597-a2aa-11ec-9299-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

{
  "category": "Fish",
  "imageUrl": "google.photos"
}

###
DELETE http://localhost:8080/category/2d38b209-ab3f-11ec-bae3-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY


####################################################################################################################
#
# Product #
#
####################################################################################################################

###
POST http://localhost:8080/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

{
  "name": "Octopus",
  "price": 10,
  "weight": 1000,
  "perUnit": 100,
  "description": "Good for health",
  "imageUrl" : null,
  "category": "17c67597-a2aa-11ec-9299-9840bb0dae2f"
}

###
PUT http://localhost:8080/product/2bdbab39-ab48-11ec-9bb0-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

{
  "name": "squid",
  "price": 10,
  "weight": 1000,
  "perUnit": 100,
  "description": "Good for health",
  "imageUrl" : null,
  "category": "17c67597-a2aa-11ec-9299-9840bb0dae2f"
}

###
GET http://localhost:8080/product/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
GET http://localhost:8080/product/2bdbab39-ab48-11ec-9bb0-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
GET http://localhost:8080/product/category/17c67597-a2aa-11ec-9299-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
DELETE http://localhost:8080/product/3b1dabeb-ab48-11ec-9bb0-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

####################################################################################################################
#
# top product #
#
####################################################################################################################

###
GET http://localhost:8080/product/top/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
GET http://localhost:8080/product/top/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
POST http://localhost:8080/product/top/2bdbab39-ab48-11ec-9bb0-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
DELETE http://localhost:8080/product/top/2bdbab39-ab48-11ec-9bb0-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

####################################################################################################################
#
# recommedation product #
#
####################################################################################################################

###
GET http://localhost:8080/product/recommendation/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
GET http://localhost:8080/product/recommendation/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
POST http://localhost:8080/product/recommendation/2bdbab39-ab48-11ec-9bb0-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
DELETE http://localhost:8080/product/recommendation/2bdbab39-ab48-11ec-9bb0-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

####################################################################################################################
#
# wishlist #
#
####################################################################################################################

###
GET http://localhost:8080/wishlist/b8fdc2dd-ab25-11ec-accb-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
GET http://localhost:8080/wishlist/b8fdc2dd-ab25-11ec-accb-9840bb0dae2f/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
POST http://localhost:8080/wishlist/b8fdc2dd-ab25-11ec-accb-9840bb0dae2f/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
DELETE http://localhost:8080/wishlist/b8fdc2dd-ab25-11ec-accb-9840bb0dae2f/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

####################################################################################################################
#
# Cart #
#
####################################################################################################################

###
GET http://localhost:8080/cart/b8fdc2dd-ab25-11ec-accb-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
POST http://localhost:8080/cart/b8fdc2dd-ab25-11ec-accb-9840bb0dae2f/a3c02e8c-11d2-11ec-82a8-0242ac130003/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
DELETE http://localhost:8080/cart/b8fdc2dd-ab25-11ec-accb-9840bb0dae2f/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

####################################################################################################################
#
# Transaction #
#
####################################################################################################################


###
POST http://localhost:8080/transaction/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

{
  "userId": "b8fdc2dd-ab25-11ec-accb-9840bb0dae2f",
  "name": "admin",
  "total": 1110,
  "detailTransaction": [
    {
      "id": "2bdbab39-ab48-11ec-9bb0-9840bb0dae2f",
      "price": 10,
      "weight": 1000,
      "category": "Fish",
      "perUnit": 100,
      "description": "Good for health",
      "imageUrl": "",
      "name": "squid"
    },
    {
      "id": "a3c02e8c-11d2-11ec-82a8-0242ac130003",
      "price": 1100,
      "weight": 1500,
      "category": "Vegetables",
      "perUnit": 100,
      "description": "Green vegetable, good for eyes",
      "imageUrl": null,
      "name": "Broccoli"
    }
  ]
}

###
GET http://localhost:8080/transaction/b8fdc2dd-ab25-11ec-accb-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
GET http://localhost:8080/transaction/user/b8fdc2dd-ab25-11ec-accb-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY

###
DELETE http://localhost:8080/transaction/b8fdc2dd-ab25-11ec-accb-9840bb0dae2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciJ9.bOrqGMj_T8_uiDSyMhRfl9WiXcAQfupT81J8sslC8gY
